Landing page
CLRM1/home_me_fe pull request #1
Opened 2022-06-02 21:19 UTC by CLRM1

- Creates facade service patter for shelters
- Updates index page with view all shelters button

2022-06-02 21:59 UTC, ross-ian28 approved these changes

2022-06-03 01:40 UTC, Eagerlearn commented
All code working for Facades, Controller, Poros and Service.
The following code block needs to be reviewed in the SheltersService class because of a misspelled variable ('shetlers') also, do we need JSON assigned to a variable at all in this instance?:

class SheltersService

  def self.get_all_shelters
    connection = Faraday.new(url: "https://desolate-caverns-04440.herokuapp.com/api/v1/")
    response = connection.get("shelters")
    shetlers = JSON.parse(response.body, symbolize_names: true)
  end

end

2022-06-03 01:45 UTC, Eagerlearn requested changes
See prior comment

2022-06-03 02:13 UTC, Eagerlearn commented
Team reviewed PR together and made needed change

2022-06-03 02:14 UTC, merged